name: intellicane
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.2.3 <4.0.0"

dependencies:
  cloud_firestore: ^4.14.0
  firebase_core: ^2.24.2
  flutter:
    sdk: flutter
  flutter_timer_countdown: ^1.0.7
  google_fonts: ^6.1.0
  google_maps_flutter: ^2.5.1
  path: ^1.8.3
  provider: ^6.1.1
  slidable_button: ^3.0.0+1
  sqflite: ^2.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/intellicane-logo.png
    - assets/vector-tunanetra.png
