name: intellicane
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.2.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_timer_countdown: ^1.0.7
  google_fonts: ^6.1.0
  path: ^1.8.3
  sqflite: ^2.3.0
  flutter_riverpod: ^2.5.1
  riverpod_annotation: ^2.3.5
  flutter_map: ^6.1.0
  flutter_map_geojson: ^1.0.6
  flutter_map_tappable_polyline: ^6.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  riverpod_generator: ^2.4.0
  riverpod_lint: ^2.3.10

flutter:
  uses-material-design: true
  assets:
    - assets/intellicane-logo.png
    - assets/vector-tunanetra.png
